spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/h2db/over35-samples;MODE=MYSQL
    username: sa
#      日志配置
logging:
  level:
    over35.samples.fluentmybatis: debug

