spring:
  rabbitmq:
    host: localhost
    port: 5662
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        ## 1公平 0是循环
        prefetch: 0
        concurrency: 1
        max-concurrency: 5
        retry:
          enabled: true
    dynamic: true
