spring:
  config:
    location:
  rabbitmq:
    host: localhost
    port: 5662
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        ## 1公平 0是循环
        prefetch: 0
        concurrency: 1
        max-concurrency: 5
        retry:
          enabled: true
    dynamic: true
#    publisher-confirms: true
    publisher-confirm-type: correlated
    publisher-returns: true
logging:
  config: classpath:log4j2-spring.xml
