spring:
    shardingsphere:
        sharding:
            tables:
                t_order:
                    actual-data-nodes: ds0.t_order_$->{0..1}
                    key-generator:
                        column: id
                        type: SNOWFLAKE
                    logic_table: t_order
                    table-strategy:
                        inline:
                            algorithm-expression: t_order_$->{id % 2}
                            sharding-column: id
