#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/h2/db-samples;MODE=MYSQL
#    type: com.zaxxer.hikari.HikariDataSource
#    username: sa
#    password:
#      日志配置
logging:
  level:
    samples.springboot.mybatis.repository.mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
