logging:
  level:
    samples:
      shardingjdbc:
        repository:
          mapper: debug
spring:
  shardingsphere:
    datasource:
      ds0:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:h2db/db-samples;MODE=MYSQL
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: sa
      names: ds0
    props:
      sql:
        show: true
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      data-locations: file:../db-samples/db-samples/sql/data/data.sql
      mode: always
      #      password: ${spring.datasource.password}
      schema-locations: file:sql/schema/schema.sql
  #      username: ${spring.datasource.username}