spring:
  datasource:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
#    url: jdbc:h2:file:~/h2db/over35-samples;MODE=MYSQL
    url: jdbc:mysql://127.0.0.1:3306/over35-samples?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
  h2:
    console:
      #default true。咱也可以用命令行访问好数据库，感兴趣的同学点这个链接 http://www.h2database.com/html/tutorial.html?highlight=Mac&search=mac#firstFound
      enabled: true
      #console url。Spring启动后，可以访问 http://127.0.0.1:8080/h2-console 查看数据库
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
        web-admin-password:
  sql:
    init:
      data-locations: classpath*:sql/data/data.sql
      mode: always
      #      password: ${spring.datasource.password}
      schema-locations: classpath*:sql/schema/schema.sql

