spring:
  datasource:
    driver-class-name: org.h2.Driver
#    password:
    url: jdbc:h2:file:~/h2db/db-samples;MODE=MYSQL
#    username: sa
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.H2Dialect

#      日志配置
logging:
  level:
    samples.jpa.repository: debug
